apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    deploy: server
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30500
    name: flask
  selector:
    deploy: server
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    deploy: mongo
spec:
  type: NodePort
  ports:
  - port: 27017
    targetPort: 27017
    nodePort: 30017
    name: db
  selector:
    deploy: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: zookeper
spec:
  type: NodePort
  ports:
  - port: 2181
    targetPort: 2181
    nodePort: 30181
    name: zookeper
  selector:
    deploy: zookeper
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  type: NodePort
  ports:
  - port: 9092
    targetPort: 9092
    nodePort: 30092
    name: kafka
  selector:
    deploy: kafka
